export { HomePage } from './HomePage'
export { ShopPage } from './ShopPage'
export { ProductPage } from './ProductPage'
export { CollectionsPage } from './CollectionsPage'
export { CollectionPage } from './CollectionPage'
export { NotFoundPage } from './NotFoundPage'
